spring:
  datasource:
    url: jdbc:h2:mem:emsdb
    driver-class-name: org.h2.Driver
    username: ems
    password: ems_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO